# Generated by Django 6.0.7 on 2026-07-31 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'کاربری با این ایمیل قبلا ثبت نام کرده است.'}, max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید ۱۱ رقم بوده و با ۰۹ شروع شود.', regex='09\\d{9}$')], verbose_name='آدرس ایمیل'),
        ),
    ]
