# Generated by Django 6.0.7 on 2026-07-31 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'کاربری با این ایمیل قبلا ثبت نام کرده است.'}, max_length=254, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید 11 رقم بوده و با 09 شروع شود.', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
